version: "3.9"

services:
  db:
    image: postgres:15
    container_name: configsync-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - configsync_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql

  backend:
    build: .
    container_name: configsync-backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY}
      PROJECT_NAME: ${PROJECT_NAME}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  redis:
    image: redis:7
    container_name: configsync-redis
    ports:
      - "${REDIS_PORT}:6379"

  worker:
    build: .
    container_name: configsync-worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - backend
      - redis
      - db

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: configsync-airflow
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://configsync:configsync@db:5432/airflow_db
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=yourfernetkeyhere
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: bash -c "
      airflow db check || airflow db init;
      sleep 5;
      airflow users create \
      -u admin -p admin -r Admin -e admin@example.com -f Admin -l User || true;
      exec airflow webserver"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: configsync-scheduler
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://configsync:configsync@db:5432/airflow_db
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=yourfernetkeyhere
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: bash -c "
      sleep 5;
      exec airflow scheduler"

volumes:
  configsync_data:
